

name: 'Node'

on:
  push:

jobs:
  run:

    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout ğŸ±â€ğŸ‘¤'
      uses: actions/checkout@v4
    - name: 'set up de node ğŸ±â€ğŸ'
      uses: actions/setup-node@v3

      with:
      
        node-version: 18
    - name: 'install dependencies ğŸ±â€ğŸ’»'
      run: npm ci

    - name: 'build javascript ğŸ±â€ğŸ‘“'
      run: npm run build

    - name: 'Lint code ğŸ±â€ğŸ‘¤'
      run: npm run lint

    - name: 'Run tests ğŸ±â€'
      run: npm run test
      
    
