#nombre del workflow, se  recomienda poner el mismo que el del archvio

name: 'Node'

#cuando queremos que se este ejecuatando
on:
  push:

jobs:
  run:

    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout ğŸ±â€ğŸ‘¤'
      uses: actions/checkout@v4
    - name: 'set up de node ğŸ±â€ğŸ'
      uses: actions/setup-node@v3

      with:
      # para especificar el nombre del archivo que va a usar
        #node-version-file: '.nvmrc'
        node-version: 18
    - name: 'install dependencies ğŸ±â€ğŸ’»'
      run: npm install

    - name: 'build javascript ğŸ±â€ğŸ‘“'
      run: npm run build #&& find dist/main.js

    - name: 'Lint code ğŸ±â€ğŸ‘¤'
      run: npm run lint

    - name: 'Run tests ğŸ±â€'
      run: npm test
      
    
